### ISSUE TITLE
Monkey problem

### ISSUE THREAD

**Issue by nigel73** [r333mo/xmas_countdown#1]
I like monkeys.

The pet store was selling them for five cents a piece. I thought that odd since they were normally a couple thousand. I decided not to look a gift horse in the mouth. I bought 200.

I took my 200 monkeys home. I have a big car. I let one drive. His name was Sigmund. He was retarded. In fact, none of them were really bright. They kept punching themselves in their genitals. I laughed. Then they punched my genitals. I stopped laughing.

I herded them into my room. They didn't adapt very well to their new environment. They would screech, hurl themselves off of the couch at high speeds and slam into the wall.

Although humourous at first, the spectacle lost its novelty halfway into its third hour.

Two hours later I found out why all the monkeys were so inexpensive: they all died. No apparent reason. They all just sorta' dropped dead. Kinda' like when you buy a goldfish and it dies five hours later. Damn cheap monkeys.

I didn't know what to do. There were 200 dead monkeys lying all over my room, on the bed, in the dresser, hanging from my bookcase. It looked like I had 200 throw rugs.

I tried to flush one down the toilet. It didn't work. It got stuck. Then I had one dead, wet monkey and 199 dead, dry monkeys.

I tried pretending that they were just stuffed animals. That worked for a while, that is until they began to decompose. It started to smell real bad.

I had to pee but there was a dead monkey in the toilet and I didn't want to call the plumber. I was embarrassed.

I tried to slow down the decomposition by freezing them. Unfortunately, there was only enough room for two monkeys at a time so I had to change them every 30 seconds. I also had to eat all the food in the freezer so it didn't all go bad.

I tried burning them. Little did I know my bed was flammable. I had to extinguish the fire.

Then I had one dead, wet monkey in my toilet, two dead, frozen monkeys in my freezer, and 197 dead, charred monkeys in a pile on my bed. The odour wasn't improving.

I became agitated at my inability to dispose of my monkeys and to use the bathroom. I severely beat one of my monkeys. I felt better.

I tried throwing them away but the garbage man said that the city was not allowed to dispose of charred primates. I told him that I had a wet one. He couldn't take that one either. I didn't bother asking about the frozen ones.

I finally arrived at a solution. I gave them out as Christmas gifts. My friends didn't know quite what to say. They pretended that they like them, but I could tell they were lying.

Ingrates.

So I punched them in the genitals.

I like monkeys.

**Comment by liu7d7** [comment]
lmao wtf

**Comment by nigel73** [comment]
i fixed the monkey issue

**Comment by nhtoTheMonke** [comment]
I like monkeys.

The pet store was selling them for five cents a piece. I thought that odd since they were normally a couple thousand. I decided not to look a gift horse in the mouth. I bought 200.

I took my 200 monkeys home. I have a big car. I let one drive. His name was Sigmund. He was retarded. In fact, none of them were really bright. They kept punching themselves in their genitals. I laughed. Then they punched my genitals. I stopped laughing.

I herded them into my room. They didn't adapt very well to their new environment. They would screech, hurl themselves off of the couch at high speeds and slam into the wall.

Although humourous at first, the spectacle lost its novelty halfway into its third hour.

Two hours later I found out why all the monkeys were so inexpensive: they all died. No apparent reason. They all just sorta' dropped dead. Kinda' like when you buy a goldfish and it dies five hours later. Damn cheap monkeys.

I didn't know what to do. There were 200 dead monkeys lying all over my room, on the bed, in the dresser, hanging from my bookcase. It looked like I had 200 throw rugs.

I tried to flush one down the toilet. It didn't work. It got stuck. Then I had one dead, wet monkey and 199 dead, dry monkeys.

I tried pretending that they were just stuffed animals. That worked for a while, that is until they began to decompose. It started to smell real bad.

I had to pee but there was a dead monkey in the toilet and I didn't want to call the plumber. I was embarrassed.

I tried to slow down the decomposition by freezing them. Unfortunately, there was only enough room for two monkeys at a time so I had to change them every 30 seconds. I also had to eat all the food in the freezer so it didn't all go bad.

I tried burning them. Little did I know my bed was flammable. I had to extinguish the fire.

Then I had one dead, wet monkey in my toilet, two dead, frozen monkeys in my freezer, and 197 dead, charred monkeys in a pile on my bed. The odour wasn't improving.

I became agitated at my inability to dispose of my monkeys and to use the bathroom. I severely beat one of my monkeys. I felt better.

I tried throwing them away but the garbage man said that the city was not allowed to dispose of charred primates. I told him that I had a wet one. He couldn't take that one either. I didn't bother asking about the frozen ones.

I finally arrived at a solution. I gave them out as Christmas gifts. My friends didn't know quite what to say. They pretended that they like them, but I could tell they were lying.

Ingrates.

So I punched them in the genitals.

I like monkeys.
